// Owner-only PRISM program reader.
//
// This function returns the same response shape the frontend
// OwnerPrismDataPanel expects: { success, program, modules, artifacts,
// warnings, error, timestamp }.
//
// On this Base44 plan, the entity layer (CanonicalProgram, CanonicalModule,
// CanonicalGeneratedArtifact) is not provisioned: `npx base44 entities push`
// is blocked with "This endpoint is only available for Backend Platform apps".
// Until that is resolved (either by upgrading the app or by creating those
// schemas manually in the dashboard), the PRISM_DTJL data lives inline in
// this function file. It is still server-side: never bundled into the public
// frontend, never visible to non-owners, and gated by requireOwnerAdmin.
//
// When entities become available, the inline branch below can be replaced
// with the entity-based read path (filter CanonicalProgram by program_key,
// then CanonicalModule + CanonicalGeneratedArtifact).
//
// Inlined policy helpers below (Base44 deploy cannot resolve ../_shared/
// imports on this app; see canary2 isolation experiment 2026-05-27).
import { createClientFromRequest } from "npm:@base44/sdk@0.8.25";

function nowIso() {
  return new Date().toISOString();
}

function safeErrorMessage(error: unknown) {
  if (error instanceof Error && error.message) {
    if (/token|secret|authorization|oauth|bearer/i.test(error.message)) {
      return "Connector request failed without exposing credentials.";
    }
    return error.message.slice(0, 240);
  }
  return "Unknown connector error.";
}

const OWNER_ROLES = new Set(["admin", "owner"]);

function rolesRecordList(response: any) {
  if (Array.isArray(response)) return response;
  if (Array.isArray(response?.data)) return response.data;
  if (Array.isArray(response?.items)) return response.items;
  if (Array.isArray(response?.records)) return response.records;
  return [];
}

function collectRoles(value: unknown, key = "", roles: string[] = []) {
  const roleKeys = new Set([
    "role",
    "roles",
    "portal_role",
    "app_role",
    "app_roles",
    "app_user_role",
    "user_role",
    "permissions",
  ]);
  const ownerFlagKeys = new Set(["is_admin", "admin", "isOwner", "is_owner"]);

  if (value == null) return roles;
  if (typeof value === "boolean" && ownerFlagKeys.has(key) && value) {
    roles.push("admin");
    return roles;
  }
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    if (roleKeys.has(key)) roles.push(String(value));
    return roles;
  }
  if (Array.isArray(value)) {
    value.forEach((item) => collectRoles(item, key, roles));
    return roles;
  }
  if (typeof value === "object") {
    Object.entries(value as Record<string, unknown>).forEach(([nextKey, nextValue]) =>
      collectRoles(nextValue, nextKey, roles),
    );
  }
  return roles;
}

async function requireOwnerAdmin(base44: any) {
  const currentUser = await base44.auth.me();
  const email = String(currentUser?.email || "").toLowerCase();
  const roleSources: unknown[] = [currentUser];

  if (email) {
    try {
      const matchingUsers = await base44.asServiceRole.entities.User.filter(
        { email },
        "-updated_date",
        5,
      );
      const appUser =
        rolesRecordList(matchingUsers).find(
          (record: Record<string, unknown>) =>
            String(record?.email || "").toLowerCase() === email,
        ) || rolesRecordList(matchingUsers)[0];
      if (appUser) roleSources.push(appUser);
    } catch (_error) {
      // role enrichment is best-effort
    }
  }

  const roles = roleSources
    .flatMap((source) => collectRoles(source))
    .map((role) => role.toLowerCase());
  if (!roles.some((role) => OWNER_ROLES.has(role))) {
    throw new Error("Owner/admin role required for this backend action.");
  }

  return { email, roles: [...new Set(roles)] };
}

// Inlined PRISM_DTJL data (owner-private). Sync from canonical_spine/ via:
//   npm run sync:prism-inline
// @spine-inline-begin — generated by scripts/sync-prism-dtjl-inline.mjs
const PRISM_DTJL_PROGRAM = {
  "program_key": "PRISM_DTJL",
  "title": "Design Thinking for a Joyful Life",
  "internal_system_name": "The Catalyst Blueprint",
  "program_family": "PRISM Core framework",
  "ownership_rail": "PRISM_CORE",
  "visibility_scope": "prism_private",
  "status": "live_private_mirror",
  "description": "The student is not broken. Current behavior is treated as data, adaptation, incomplete design, or untested assumption. Students may experience stuckness, shame, procrastination, choice paralysis, low self-efficacy, environmental drag, and uncertainty about future direction.",
  "demo_summary": "A PRISM-owned framework for helping young adults turn stuckness, information overload, and future uncertainty into clear design questions, prototype actions, and safer learning artifacts. Demo mode shows only this high-level overview.",
  "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
  "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
  "github_repo": "tbm898-source/canonical (private)",
  "source_version": "v0.1",
  "audience": "Youth ages 18-24",
  "program_type": "developmental education and life design curriculum",
  "delivery_modes": [
    "classroom workshop",
    "pre-apprenticeship support module",
    "coaching-style reflection",
    "Google Classroom package",
    "agent-generated workbook"
  ],
  "required_agent_rules": [
    "Diagnose before advising.",
    "Never equate behavior with character.",
    "Treat procrastination as possible self-protection before treating it as laziness.",
    "Never generate only one future path.",
    "Prefer prototypes over major leaps.",
    "Prefer environment redesign over willpower lectures.",
    "Mark claims by evidence status.",
    "Do not diagnose mental health conditions.",
    "Do not present practitioner tools as clinical laws."
  ],
  "evidence_status": "mixed_requires_review",
  "allowed_exports": [
    "owner_json",
    "owner_markdown",
    "future_curated_demo"
  ],
  "default_demo_behavior": "public_demo_summary_only",
  "boundary_statement": "PRISM_DTJL is PRISM Core, private-first, demo-summary-only, and not AYA implementation.",
  "owner_only_notes_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life/90_REVIEW/NEXT_ACTIONS.md",
  "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
  "created_at": "2026-05-25T00:00:00.000Z",
  "updated_at": "2026-06-03T06:12:13.954Z"
};

const PRISM_DTJL_MODULES = [
  {
    "program_key": "PRISM_DTJL",
    "module_key": "CATALYST_BLUEPRINT_V0_1",
    "title": "The Catalyst Blueprint v0.1",
    "status": "live_private_mirror",
    "visibility_scope": "prism_private",
    "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "source_version": "v0.1",
    "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
    "sequence_order": 0,
    "description": "Root scaffold module for the PRISM_DTJL program OS, curriculum sequence, and agent pack."
  },
  {
    "program_key": "PRISM_DTJL",
    "module_key": "DTJL_M01_CRITICAL_THINKING",
    "title": "Critical Thinking and Information Navigation",
    "status": "curriculum_module_v0_1",
    "visibility_scope": "prism_private",
    "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life/04_CURRICULUM/MODULE_SEQUENCE.md",
    "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "source_version": "v0.1",
    "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
    "sequence_order": 1,
    "description": "Curriculum module 1 of 6 in the Catalyst Blueprint sequence."
  },
  {
    "program_key": "PRISM_DTJL",
    "module_key": "DTJL_M02_LIFE_DESIGN_LAB",
    "title": "Life Design Lab",
    "status": "curriculum_module_v0_1",
    "visibility_scope": "prism_private",
    "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life/04_CURRICULUM/MODULE_SEQUENCE.md",
    "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "source_version": "v0.1",
    "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
    "sequence_order": 2,
    "description": "Curriculum module 2 of 6 in the Catalyst Blueprint sequence."
  },
  {
    "program_key": "PRISM_DTJL",
    "module_key": "DTJL_M03_ODYSSEY_PLANNING",
    "title": "Odyssey Planning and Prototyping",
    "status": "curriculum_module_v0_1",
    "visibility_scope": "prism_private",
    "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life/04_CURRICULUM/MODULE_SEQUENCE.md",
    "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "source_version": "v0.1",
    "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
    "sequence_order": 3,
    "description": "Curriculum module 3 of 6 in the Catalyst Blueprint sequence."
  },
  {
    "program_key": "PRISM_DTJL",
    "module_key": "DTJL_M04_HIGH_SPEED_CHANGE",
    "title": "Mechanics of High-Speed Change",
    "status": "curriculum_module_v0_1",
    "visibility_scope": "prism_private",
    "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life/04_CURRICULUM/MODULE_SEQUENCE.md",
    "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "source_version": "v0.1",
    "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
    "sequence_order": 4,
    "description": "Curriculum module 4 of 6 in the Catalyst Blueprint sequence."
  },
  {
    "program_key": "PRISM_DTJL",
    "module_key": "DTJL_M05_ENVIRONMENT_ARCHITECTURE",
    "title": "Environmental Architecture and Resilience",
    "status": "curriculum_module_v0_1",
    "visibility_scope": "prism_private",
    "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life/04_CURRICULUM/MODULE_SEQUENCE.md",
    "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "source_version": "v0.1",
    "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
    "sequence_order": 5,
    "description": "Curriculum module 5 of 6 in the Catalyst Blueprint sequence."
  },
  {
    "program_key": "PRISM_DTJL",
    "module_key": "DTJL_M06_DECISION_ARCHITECTURE",
    "title": "Decision Architecture",
    "status": "curriculum_module_v0_1",
    "visibility_scope": "prism_private",
    "canonical_path": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life/04_CURRICULUM/MODULE_SEQUENCE.md",
    "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
    "source_version": "v0.1",
    "created_from_import_id": "import_prism_dtjl_2026_05_25_v0_1",
    "sequence_order": 6,
    "description": "Curriculum module 6 of 6 in the Catalyst Blueprint sequence."
  }
];

const PRISM_DTJL_ARTIFACTS = [
  {
    "artifact_id": "prism_dtjl_source_structure_index_v0_1",
    "module_key": "CATALYST_BLUEPRINT_V0_1",
    "session_key": "",
    "session_title": "PRISM_DTJL source structure index",
    "title": "PRISM_DTJL Source Structure Index",
    "rail": "prism",
    "visibility_scope": "prism_private",
    "artifact_type": "manifest",
    "audience": "operator",
    "format": "json",
    "privacy_level": "restricted",
    "status": "approved",
    "version": "v0.1",
    "generated_json": {
      "source_structure": [
        "00_GOVERNANCE",
        "01_SOURCES",
        "02_PROGRAM_OS",
        "03_AGENT_SKILLS",
        "04_CURRICULUM",
        "05_ARTIFACT_RECIPES",
        "06_ASSESSMENTS",
        "07_EXPORTS",
        "90_REVIEW",
        "IMPORT_MANIFEST.json"
      ],
      "canonical_root": "CANONICAL://02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
      "repo_mirror_path": "canonical_spine/02_PROJECTS/PRISM/programs/design-thinking-for-a-joyful-life",
      "boundary_statement": "PRISM_DTJL is PRISM Core, private-first, demo-summary-only, and not AYA implementation."
    },
    "warnings": [
      "Owner-only. Do not export to AYA classroom, public demo, or Google Classroom destinations."
    ]
  },
  {
    "artifact_id": "prism_dtjl_program_manifest_v0_1",
    "module_key": "CATALYST_BLUEPRINT_V0_1",
    "session_key": "",
    "session_title": "Program manifest",
    "title": "PROGRAM_MANIFEST.json",
    "rail": "prism",
    "visibility_scope": "prism_private",
    "artifact_type": "program_os",
    "audience": "operator",
    "format": "json",
    "privacy_level": "restricted",
    "status": "approved",
    "version": "v0.1",
    "generated_json": {
      "program_id": "design_thinking_for_a_joyful_life_v0_1",
      "program_title": "Design Thinking for a Joyful Life",
      "internal_system_name": "The Catalyst Blueprint",
      "version": "0.1",
      "audience": "Youth ages 18-24",
      "program_type": "developmental education and life design curriculum",
      "scope": "PRISM_CORE",
      "core_problem": "Students may experience stuckness, shame, procrastination, choice paralysis, low self-efficacy, environmental drag, and uncertainty about future direction.",
      "core_reframe": "The student is not broken. Current behavior is treated as data, adaptation, incomplete design, or untested assumption.",
      "delivery_modes": [
        "classroom workshop",
        "pre-apprenticeship support module",
        "coaching-style reflection",
        "Google Classroom package",
        "agent-generated workbook"
      ],
      "core_modules": [
        "Critical Thinking and Information Navigation",
        "Life Design Lab",
        "Odyssey Planning and Prototyping",
        "Mechanics of High-Speed Change",
        "Environmental Architecture and Resilience",
        "Decision Architecture"
      ],
      "required_agent_rules": [
        "Diagnose before advising.",
        "Never equate behavior with character.",
        "Treat procrastination as possible self-protection before treating it as laziness.",
        "Never generate only one future path.",
        "Prefer prototypes over major leaps.",
        "Prefer environment redesign over willpower lectures.",
        "Mark claims by evidence status.",
        "Do not diagnose mental health conditions.",
        "Do not present practitioner tools as clinical laws."
      ]
    },
    "warnings": []
  },
  {
    "artifact_id": "prism_dtjl_program_os_summary_v0_1",
    "module_key": "CATALYST_BLUEPRINT_V0_1",
    "session_key": "",
    "session_title": "Program OS summary",
    "title": "Concept / diagnostic / intervention index",
    "rail": "prism",
    "visibility_scope": "prism_private",
    "artifact_type": "program_os",
    "audience": "operator",
    "format": "json",
    "privacy_level": "restricted",
    "status": "approved",
    "version": "v0.1",
    "generated_json": {
      "concept_count": 7,
      "concepts": [
        {
          "id": "concept.self_worth_equation",
          "label": "Self-Worth Equation",
          "evidence_status": "research_supported_needs_specific_citation"
        },
        {
          "id": "concept.procrastination_as_self_protection",
          "label": "Procrastination as Self-Protection",
          "evidence_status": "research_supported_needs_specific_citation"
        },
        {
          "id": "concept.gravity_problem",
          "label": "Gravity Problem",
          "evidence_status": "published_framework"
        },
        {
          "id": "concept.odyssey_planning",
          "label": "Odyssey Planning",
          "evidence_status": "published_framework"
        },
        {
          "id": "concept.activation_energy",
          "label": "Activation Energy",
          "evidence_status": "practitioner_framework"
        },
        {
          "id": "concept.environment_over_willpower",
          "label": "Environment Over Willpower",
          "evidence_status": "research_supported_needs_specific_citation"
        },
        {
          "id": "concept.fact_vs_argument",
          "label": "Fact vs Argument",
          "evidence_status": "teaching_framework"
        }
      ],
      "diagnostic_pattern_count": 4,
      "diagnostic_patterns": [
        {
          "id": "diagnostic.self_worth_threat"
        },
        {
          "id": "diagnostic.choice_overload"
        },
        {
          "id": "diagnostic.gravity_problem"
        },
        {
          "id": "diagnostic.activation_latency"
        }
      ],
      "intervention_count": 5,
      "interventions": [
        {
          "id": "intervention.decouple_worth_from_performance",
          "name": "Worth Decoupling Protocol"
        },
        {
          "id": "intervention.small_win_protocol",
          "name": "Small Win Protocol"
        },
        {
          "id": "intervention.odyssey_planning",
          "name": "Three Futures / Odyssey Planning"
        },
        {
          "id": "intervention.twenty_hour_skill_sprint",
          "name": "20-Hour Skill Sprint"
        },
        {
          "id": "intervention.authority_audit",
          "name": "Intentional Authority Audit"
        }
      ]
    },
    "warnings": []
  }
];
// @spine-inline-end

function emptyPayload(extra: Record<string, unknown> = {}) {
  return {
    success: false,
    program: null,
    modules: [],
    artifacts: [],
    warnings: [] as string[],
    timestamp: nowIso(),
    error: null as string | null,
    ...extra,
  };
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    try {
      await requireOwnerAdmin(base44);
    } catch (error) {
      return Response.json(
        emptyPayload({ error: safeErrorMessage(error) }),
        { status: 403 },
      );
    }

    const payload = await req.json().catch(() => ({}));
    const programKey = String(
      (payload as { program_key?: unknown })?.program_key || "",
    ).trim();

    if (!programKey) {
      return Response.json(
        emptyPayload({ error: "program_key is required." }),
        { status: 200 },
      );
    }

    if (programKey === "PRISM_DTJL") {
      return Response.json(
        {
          success: true,
          program: PRISM_DTJL_PROGRAM,
          modules: PRISM_DTJL_MODULES,
          artifacts: PRISM_DTJL_ARTIFACTS,
          warnings: [
            "PRISM_DTJL is served live from the private GitHub canonical_spine mirror via this owner-only function.",
            "Entity-backed reads remain future work when the Base44 entity layer is provisioned on this app.",
          ],
          timestamp: nowIso(),
          error: null,
        },
        { status: 200 },
      );
    }

    return Response.json(
      {
        success: true,
        program: null,
        modules: [],
        artifacts: [],
        warnings: [
          `No inline data for program_key="${programKey}". Only PRISM_DTJL is currently served inline. Other programs require the entity layer, which is not provisioned on this app's plan.`,
        ],
        timestamp: nowIso(),
        error: null,
      },
      { status: 200 },
    );
  } catch (error) {
    return Response.json(
      emptyPayload({ error: safeErrorMessage(error) }),
      { status: 200 },
    );
  }
});
