import React from "react";
import { motion } from "framer-motion";
import { ArrowLeft, BrainCircuit, FileStack, GitBranch, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

const fadeUp = {
  hidden: { opacity: 0, y: 22 },
  visible: (i = 0) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.08, duration: 0.55, ease: [0.22, 1, 0.36, 1] },
  }),
};

const principles = [
  {
    icon: FileStack,
    title: "Memory survives the tool",
    text: "The file spine remains authoritative even when materials are drafted in chat, generated by agents, exported to Classroom, or mirrored into an app.",
  },
  {
    icon: GitBranch,
    title: "Rails stay separate",
    text: "AYA / CTS delivery materials, PRISM framework material, public demo summaries, and private operator notes are classified before they are shown or exported.",
  },
  {
    icon: BrainCircuit,
    title: "Agents draft, owners approve",
    text: "AI helpers can normalize context and prepare artifacts, but live writes, public exports, and official records require review.",
  },
];

function BrandMark() {
  return (
    <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#0a0a0a]">
      <span className="text-xs font-bold tracking-tight text-white">C</span>
    </div>
  );
}

export default function About() {
  return (
    <div className="min-h-screen bg-[#fafafa]">
      <nav className="fixed left-0 right-0 top-0 z-50 border-b border-black/5 bg-[#fafafa]/85 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
          <Link to="/Home" className="flex items-center gap-2">
            <BrandMark />
            <span className="text-[15px] font-semibold tracking-tight text-[#0a0a0a]">
              CANONICAL
            </span>
          </Link>
          <Link to="/Home">
            <Button variant="ghost" size="sm" className="gap-2 text-[#0a0a0a]/50 hover:text-[#0a0a0a]">
              <ArrowLeft className="h-4 w-4" />
              Home
            </Button>
          </Link>
        </div>
      </nav>

      <main className="px-6 pb-24 pt-36">
        <motion.div initial="hidden" animate="visible" className="mx-auto max-w-6xl">
          <motion.div variants={fadeUp} custom={0} className="max-w-3xl">
            <p className="mb-5 text-xs font-semibold uppercase tracking-widest text-indigo-600">
              About CANONICAL
            </p>
            <h1 className="text-4xl font-bold leading-tight tracking-tight text-[#0a0a0a] sm:text-6xl">
              A stable spine for work that keeps trying to scatter.
            </h1>
            <p className="mt-8 text-lg leading-8 text-[#0a0a0a]/50">
              CANONICAL was built to solve a practical problem: important work gets scattered across chats, drives, folders, classrooms, dashboards, agent outputs, and human memory. CANONICAL gives that work a stable spine.
            </p>
          </motion.div>

          <section className="mt-16 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">
            <motion.div variants={fadeUp} custom={1} className="rounded-3xl border border-black/5 bg-white p-7 shadow-sm">
              <ShieldCheck className="mb-5 h-9 w-9 text-indigo-600" />
              <h2 className="text-2xl font-bold tracking-tight text-[#0a0a0a]">
                The boundary is the architecture.
              </h2>
              <p className="mt-4 text-sm leading-6 text-[#0a0a0a]/50">
                AYA / CTS materials stay classroom-facing, practical, and institutionally clean. PRISM materials stay framework-facing, facilitator/operator-oriented, and separately attributed.
              </p>
              <p className="mt-4 rounded-2xl bg-indigo-50 p-4 text-sm leading-6 text-indigo-900">
                PRISM_DTJL is PRISM Core, private-first, demo-summary-only, and not AYA implementation.
              </p>
            </motion.div>

            <motion.div variants={fadeUp} custom={2} className="grid gap-3">
              {principles.map((principle, i) => (
                <article key={principle.title} className="rounded-2xl border border-black/5 bg-white p-5 shadow-sm">
                  <div className="flex gap-4">
                    <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-indigo-50">
                      <principle.icon className="h-5 w-5 text-indigo-600" />
                    </div>
                    <div>
                      <h3 className="text-base font-semibold text-[#0a0a0a]">{principle.title}</h3>
                      <p className="mt-2 text-sm leading-6 text-[#0a0a0a]/50">{principle.text}</p>
                    </div>
                  </div>
                </article>
              ))}
            </motion.div>
          </section>

          <section className="mt-16 rounded-3xl border border-black/5 bg-[#0a0a0a] p-8 text-white sm:p-12">
            <div className="max-w-3xl">
              <h2 className="text-3xl font-bold tracking-tight">Current public posture</h2>
              <p className="mt-4 text-sm leading-6 text-white/55">
                CANONICAL is currently in private operator buildout. Public materials shown here are overview-level only. Demo mode intentionally avoids private Dropbox paths, raw PRISM notes, source internals, credentials, backend logs, and live connector actions.
              </p>
            </div>
          </section>
        </motion.div>
      </main>
    </div>
  );
}
